version: '3.8'

services:
  # Backend API Service
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    container_name: headless-pm-api
    ports:
      - "6969:6969"
    environment:
      - PORT=6969
      - DATABASE_URL=sqlite:///app/database/headless-pm.db
      - PYTHONPATH=/app
    volumes:
      - ./database:/app/database
      - ./projects:/app/projects
      - ./agents:/app/agents
      - ./shared:/app/shared
    networks:
      - headless-pm-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6969/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # MCP Server Service
  mcp:
    build:
      context: .
      dockerfile: mcp/Dockerfile
    container_name: headless-pm-mcp
    ports:
      - "6968:6968"
    environment:
      - MCP_PORT=6968
      - API_BASE_URL=http://api:6969
      - PYTHONPATH=/app
    volumes:
      - ./projects:/app/projects
      - ./agents:/app/agents
      - ./shared:/app/shared
    depends_on:
      api:
        condition: service_healthy
    networks:
      - headless-pm-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pgrep", "-f", "mcp.src"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Dashboard UI Service
  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: headless-pm-dashboard
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NEXT_PUBLIC_API_URL=http://localhost:6969
      - NODE_ENV=production
    depends_on:
      api:
        condition: service_healthy
    networks:
      - headless-pm-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  headless-pm-network:
    driver: bridge

volumes:
  headless-pm-data:
    driver: local